### ISSUE TITLE
Encryption and Frequency Analysis

### ISSUE THREAD

**Issue by green7ea** [bitpost-team/bitpost#1]
The proposed encryption scheme seems to be vulnerable to frequency analysis ([wikipedia](https://en.wikipedia.org/wiki/Frequency_analysis)). This would affect every message and be even more problematic for longer messages where decrypting would become trivial. An easy way to limit this would be to have the alphaList change based on the message content. This would help but is probably still vulnerable.

Rolling your own crypto is very hard, you may want to consider:

- [saltpack](https://saltpack.org/),
- [noise protocol](https://noiseprotocol.org/).

**Comment by awnumar** [comment]
> An easy way to limit this would be to have the alphaList change based on the message content

I doubt this will fix the issue. Sounds more like [Vigenère](https://en.wikipedia.org/wiki/Vigen%C3%A8re_cipher), which is also broken (a long time ago).

[Cryptography](https://cryptography.io/en/latest/) is a good choice for a secure and easy to use library that provides access to **standard** cryptographic tools.

**Comment by samuelezraberry** [comment]
This was all while developing and researching crypto. Currently I'm working on a new algorithm that is more secure but is also backed by pgp
